site_name: Guia de Estilo para Traduções e Transcrições em Português (Brasil) no TED Translators
pages:
    - Home: index.md
    - Números e Numerais: numeros_numerais.md
    - Unidades de Medida: unidades_medida.md
    - Estrangeirismos: estrangeirismos.md
    - Uso das Aspas no Discurso Direto: aspasdireto.md
theme: readthedocs